### ISSUE TITLE
Can we get calories burnt?

### ISSUE THREAD

**Issue by IntelliJAbhishek** [OvalMoney/react-native-fitness#16]
How can we get calories burnt by steps. Its already exposed by google fit?

**Comment by Francesco-Voto** [comment]
Sorry, this feature is not yet implemented., but it will be as soon as possible, since we are programming next step.

**Comment by anshul12** [comment]
@Francesco-Voto By when are you planning to push new methods. 
I need this for some of my POCs. Please let me know so that I can plan accordingly. Thanks in advance.

**Comment by Francesco-Voto** [comment]
Sorry for late reply. 
Actually we are planning the next steps: a bit refactor will be available in next weeks. this will include also new methods.
Thanks for the interest.

**Comment by anshulsingh2403** [comment]
@Francesco-Voto 
Are these change available ?
