### ISSUE TITLE
0.60 support?

### ISSUE THREAD

**Issue by dmitov** [OvalMoney/react-native-fitness#17]
Hi guys, good stuff!

I'm interested what's the support for RN 0.60 and automatic linking?

Also, is there a roadmap or a feature list so I can help with the development?

**Comment by scerelli** [comment]
Hi @dmitov, ye we have planned to integrate RN 60 asap, for the roadmap we don't have any, sorry. If you would like to see any feature added to this package I suggest you to simply open an issue with the feature request, so we can plan if it's something interesting to have for the community. Btw any help is well accepted :)

**Comment by pie6k** [comment]
So it is not working with the newest version of RN right now?

**Comment by scerelli** [comment]
@pie6k yes, it works also for rn 61. We're using it in production.
