### ISSUE TITLE
Can we specify permissions for other HealthKit or Google Fit parameters?

### ISSUE THREAD

**Issue by ShaharyarMaroof** [OvalMoney/react-native-fitness#19]

**Comment by scerelli** [comment]
what do you mean @ShaharyarMaroof ?

**Comment by ShaharyarMaroof** [comment]
So can we specify which metrics, the app can read/write to, e.g. the Calorie Count or BMI? Or does this lib provide access to all the metrics provide by the HealthKit and Google Fitness API?

**Comment by scerelli** [comment]
@Francesco-Voto

**Comment by Francesco-Voto** [comment]
I am working to be more flexible on the metrics. It will be available in next releases.

**Comment by Francesco-Voto** [comment]
Now this is possibile with v0.3.0. Can you try it?
