### ISSUE TITLE
Unable to Authorize with Google Fit

### ISSUE THREAD

**Issue by ShaharyarMaroof** [OvalMoney/react-native-fitness#21]
@scerelli I am trying to authorise the app to connect to google fit, but the Fitness.requestPermissions method always returns false. Is there some specific requirements for android? I saw a merge request  #6 which was intended to allow connection even without Google Fit installed.

I am using react-native 0.60.6, lib version 0.2.4 and Android Q (API level 29) emulator. Any idea what could be wrong?

**Comment by Francesco-Voto** [comment]
Have you followed the section fro Android and create an OAuth 2.0 Client ID?

**Comment by ShaharyarMaroof** [comment]
Ah, I skipped that as it was in the manual section of the installation guide. Thanks, will look into this.

**Comment by ShaharyarMaroof** [comment]
@Francesco-Voto can you let me know, where do I have to add the API key to configure this?

**Comment by ShaharyarMaroof** [comment]
Hey @Francesco-Voto I created the key as mentioned in the Android section and since I used auto linking to link the package. but I still cannot get authorised from the Google Fit API. Any suggestions?

**Comment by Francesco-Voto** [comment]
Hi @ShaharyarMaroof. Normally this kind of problems are some misconfiguration, since no info are inserted inside the codebase, but everything is handled via OAuth 2.0. Have you found some trouble to follow the guide at https://developers.google.com/fit/android/get-api-key?

**Comment by ShaharyarMaroof** [comment]
Won't we have to provide the google client ID somewhere in the app to connect to the Fitness API?  As this lib has done? [react-native-google-fit](https://github.com/StasDoskalenko/react-native-google-fit/blob/master/docs/INSTALLATION.md)

**Comment by Francesco-Voto** [comment]
No this is not necessary. You just need to register your app in  [Google API console](https://console.developers.google.com). You need also to call ```Fitness.requestPwermissions()``` first time  you want to fetch the data.

Hope this will help. :)

**Comment by ShaharyarMaroof** [comment]
Thank you very much! :) (Y)

**Comment by iitsuraj** [comment]
For getting Oauth token, I followed (https://developers.google.com/fit/android/get-api-key), but when I ask for `Fitness.requestPwermissions()` it shows me to choose an account, and after selecting the account that screen disappears.  And Fitness.isAuthorized return false value

**Comment by rlems** [comment]
> For getting Oauth token, I followed (https://developers.google.com/fit/android/get-api-key), but when I ask for `Fitness.requestPwermissions()` it shows me to choose an account, and after selecting the account that screen disappears. And Fitness.isAuthorized return false value

@iitsuraj I'm experiencing the same issue, did you solve it?

**Comment by Francesco-Voto** [comment]
Usually this means a misconfiguration on OAuth 2.0 Client ID part.
Please note for Debug ore Release you will use different SHA-1 as well as you need to create different Client ID  if you change package name in your flavours

**Comment by rlems** [comment]
@Francesco-Voto You are right. I created the Client ID with the wrong SHA-1, not the one provided with the React Native android project. Thank you for your help

**Comment by GuleriaAshish** [comment]
@ShaharyarMaroof are you able to get data without installing Google fit app on android?

**Comment by ShaharyarMaroof** [comment]
@GuleriaAshish , I don't remember as I moved to another library.

**Comment by GuleriaAshish** [comment]
@ShaharyarMaroof Which library, Please suggest.

**Comment by shaharyarmaroof-polarr** [comment]
@GuleriaAshish I used react-native-google-fit and rn-apple-healthkit

**Comment by keiscool2468** [comment]
i already get the clientID from console.developers.google, where should i put it in.
It did not mention in the Doc / Readme

**Comment by Francesco-Voto** [comment]
Nowhere. We are using OAuth 2.0 which relies on SHA and package name you put on console
