### ISSUE TITLE
getCalories error

### ISSUE THREAD

**Issue by DeevD** [OvalMoney/react-native-fitness#25]
catch  error TypeError: _reactNativeFitness.default.getCalories is not a function

 const dates = { startDate: withinDay(7), endDate: new Date().toISOString() }
 Fitness.getCalories(dates).then(result => {
                            console.log('getCalories Result ' + JSON.stringify(result))
});

**Comment by Francesco-Voto** [comment]
I will check it as soon as possibile. Thanks for the feedback

**Comment by Francesco-Voto** [comment]
Sorry for delay. Have you solved this? Can you tell me what version of libraries are you using?

**Comment by Francesco-Voto** [comment]
Can you try with the last release please?

**Comment by Francesco-Voto** [comment]
I close for no updates on it
