### ISSUE TITLE
Can't get the latest release of this library

### ISSUE THREAD

**Issue by FuriioS** [OvalMoney/react-native-fitness#30]
Hi there!

When I try to install the latest release of this library (v0.2.5) using

`npm install @ovalmoney/react-native-fitness --save`

npm installs me the v0.2.4 instead of v0.2.5. If I enforce to install the v0.2.5 it tells me

> Couldn't find any versions for "@ovalmoney/react-native-fitness" that matches "^0.2.5"

How do I proceed?

Regards,

**Comment by Francesco-Voto** [comment]
Hi @FuriioS 
Sorry for the problem, I will check it. For now you can use the v.0.2.4 if you want. We are also planning to make a new release in next weeks

**Comment by akinncar** [comment]
some update?

**Comment by Francesco-Voto** [comment]
Can you try to got the 0.3.0 now.
Let me know

**Comment by FuriioS** [comment]
> Can you try to got the 0.3.0 now.
> Let me know

Like a charm 🔥🔥
