### ISSUE TITLE
Android promises not resolving

### ISSUE THREAD

**Issue by lblois** [OvalMoney/react-native-fitness#31]
Hi,
Thanks you for the library which works flawlessly on iOS. I am encountering an issue with the android part : whenever I try to call `Fitness.getSteps(opt)` or `Fitness.getDistance(opt)`, the promises created won't resolve nor reject.

I made sure that my SHA1 is properly authorized through the Google Fitness API & co (as other functions such as `Fitness.isAuthorized()` properly works).

I'm on RN 0.59.10 with the library at `0.2.4`

**Comment by Francesco-Voto** [comment]
Hi @lblois,

I will check as soon as possibile

**Comment by lblois** [comment]
Hi @Francesco-Voto , thanks for the support, did you get the time to check ?

**Comment by Francesco-Voto** [comment]
Can you try with the last release? (0.3.0)

**Comment by antoinedelp** [comment]
Hi @Francesco-Voto, thanks for the package! 
I am experiencing the same issue as @lblois on 0.3.0 : promises are just left hanging. It works fine on iOs and I managed to choose my Google account with Fitness.isAuthorized()

**Comment by Francesco-Voto** [comment]
Hi @antoinedelp,

Can I ask if you also see a possible pick for the permissions you would like to authorise on Android also? It should happen after you select your account

**Comment by antoinedelp** [comment]
The permissions are the following: 

> [{ kind: Fitness.PermissionKind.Step }, { kind: Fitness.PermissionKind.Distance }])

I authorized both permissions successfully.

Regarding my problem, I found the solution: I was simply passing an incorrect startDate. Once corrected, the function works as expected!

**Comment by Francesco-Voto** [comment]
Thank you for the reply! 
Maybe a better error can be useful.
