### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by ibraude** [OvalMoney/react-native-fitness#5]
Hey, 

First of all, thank you very much for the module. 
I was wondering if you could post a usage example using the getSteps method. 

I have set up the module, including the Google Client ID. 
the requestPermission method works, and I get `true` from isAuthorized, but for the getSteps method, I just get an empty array as the response and can't seem to get a step count.
` Fitness.getSteps({startDate: start, endDate:end})
           .then((response) => {console.log(response)})
           //logs []`

How would you go about using the module to get an ongoing step count? 

Any insight would be greatly appreciated. 

Thanks,

**Comment by praveen7557** [comment]
Hi @ibraude ,

Can you let me know how you did this?
I was getting this error [https://github.com/OvalMoney/react-native-fitness/issues/9](https://github.com/OvalMoney/react-native-fitness/issues/9)

**Comment by losheredos** [comment]
@ibraude I still get the empty array as you mentioned. It works on both android & IOS like authorizaiton etc. but when I get results of steps its just empty array. I thought it could be cuz of simulator but I test it in real device now, looks same..

Can anyone help about it?
