### ISSUE TITLE
Query for Immediate Values

### ISSUE THREAD

**Issue by gregermendle** [OvalMoney/react-native-fitness#51]
Hey!

I've been testing out this lib to query step count and heart rate on an interval (like every 5 seconds). I noticed that the data that is returned takes about 5 minutes to update. I was wondering if there is a way to get immediate values? I did some research on different querying mechanisms in HK but, I'm still a little unsure of if this is possible on such a short frequency.

Thanks!

**Comment by gucolin** [comment]
Same question here.

**Comment by Francesco-Voto** [comment]
Hey @gregermendle 

I guess the only way is to ask directly to the Core Motion and listen for update. 

Sorry for the moment there is no plan to introduce this part
