### ISSUE TITLE
error: null reference. when I do console.log, isAuthorized always return false, PermissionAccess.write always return undefined

### ISSUE THREAD

**Issue by philipusmartin9** [OvalMoney/react-native-fitness#63]
Hello,

First of all, great work! Im so excited to try this plugin.
I tried using this with RN 0.62, (using autolinking).
if I run without checking isAuthorized, it always gives null reference error. So, I put some console.log(s) and found out isAuthorized always return false, PermissionAccess.write always return undefined.
Did I miss a step in setting up this plugin, or maybe there's missing step in the usage?

Thanks in advance, pardon if the snippet is a bit messy

`const permissions = [
    { kind: Fitness.PermissionKind.Step, access: Fitness.PermissionAccess.Write }
];`

`const logSteps = async () => {

    console.log("permission:", permissions); // the result is {access: undefined, kind: 0}
    Fitness.isAuthorized(permissions)
      .then(async (authorized) => {
        let initialDate = new Date();
        let startDate = new Date(initialDate.getFullYear(), initialDate.getMonth(), initialDate.getDate(), 0, 0, 0);
        let endDate = new Date(initialDate.getFullYear(), initialDate.getMonth(), initialDate.getDate(), 23, 59, 59);
        let formattedStart = startDate.toISOString();
        let formattedEnd = endDate.toISOString();
        console.log('start:', formattedStart);
        console.log('end:', formattedEnd);
        // Do something
        console.log('auth result:', authorized); // always return false
        if(authorized){
          let result = await Fitness.getSteps({
            startDate: formattedStart,
            endDate: formattedEnd,
            interval: 'days'
          });
        }
      })
      .catch((error) => {
        // Do something
        console.log('Failed auth', error);
      });
  }
`

**Comment by philipusmartin9** [comment]
I finally managed to make it work by adding this to my build.gradle dependencies:

`implementation "com.google.android.gms:play-services-base:+"
implementation "com.google.android.gms:play-services-auth:+"
implementation "com.google.android.gms:play-services-fitness:+"`

the permission request works, now the authorization returns true, but I still only get empty array even though I have steps data in my google fit account. can anyone help in this? thanks

**Comment by philipusmartin9** [comment]
It works, the app can only get the google fit data in the same, not cross-device.

**Comment by Francesco-Voto** [comment]
@philipusmartin9 Thank you for explain the issue. Glad to hear it works in some way
