### ISSUE TITLE
error: cannot find symbol: variable TYPE_ACTIVITY_SAMPLES

### ISSUE THREAD

**Issue by laxminarayanmn** [OvalMoney/react-native-fitness#64]
<img width="573" alt="Screenshot 2020-08-11 at 10 20 51 PM" src="https://user-images.githubusercontent.com/36225584/89925588-45b8ec80-dc21-11ea-8fb5-3491084af864.png">

node_modules/@ovalmoney/react-native-fitness/android/src/main/java/com/ovalmoney/fitness/manager/Manager.java:145: error: cannot find symbol
                .subscribe(DataType.TYPE_ACTIVITY_SAMPLES)
                                   ^
  symbol:   variable TYPE_ACTIVITY_SAMPLES
  location: class DataType

It was working fine, suddenly stopped working today after npm install for other library

react-native 0.62.0 
@ovalmoney/react-native-fitness: 0.4.0

**Comment by Francesco-Voto** [comment]
Hi @laxminarayanmn ,
have you change the version of ```:play-services-fitness``` ?

**Comment by laxminarayanmn** [comment]
yes, Im using 'com.google.android.gms:play-services-fitness:19.0.0'

**Comment by Francesco-Voto** [comment]
It seems it does not exist anymore. I will fix it

**Comment by Francesco-Voto** [comment]
Can you use 17.0.0 for the moment?

**Comment by laxminarayanmn** [comment]
sure, i'll use the 17.0.0

**Comment by auliakbarh** [comment]
@laxminarayanmn does it works if you use 'com.google.android.gms:play-services-fitness:17.0.0' in app gradle?

**Comment by laxminarayanmn** [comment]
@auliakbarh it worked as expected when i removed `googlePlayServicesVersion = "+" `from projects gradle

**Comment by francisli** [comment]
I could use some help from anyone on this thread... my project did not have neither a dependency implementation line nor a googlePlayServicesVersion line in its build.gradle... I've tried adding them and specifying version 17.0.0, but it does not solve the compilation issue...

What has happened in just the last week or so?

**Comment by francisli** [comment]
Ok, I see the removal of the field in the release notes:

https://developers.google.com/android/guides/releases#august_10_2020

**Comment by francisli** [comment]
Ok, I see how the build.gradle for this library is written now... for anyone else visiting this thread, you can specify an older version of Google Play Services in your _top-level_ build.gradle file, for example:

```
buildscript {
    ext {
        ...
        googlePlayServicesVersion = '17.0.0'
    }
}
```

When I tried bumping down just to 18.0.0 I got an error that iid services could not be found with that version...
