### ISSUE TITLE
on IOS ,  getCalories return []

### ISSUE THREAD

**Issue by cham1985** [OvalMoney/react-native-fitness#66]
Hello everyone, my authorization is successful on ios, and both step and distance can get data, but on the debug and release packages, getCalories  method return [],  has anyone encountered this problem ?
![image](https://user-images.githubusercontent.com/7087874/91650656-c185b680-eab4-11ea-8ec9-e2fa65f9eb36.png)

**Comment by cham1985** [comment]
time period problem,solved

**Comment by GuleriaAshish** [comment]
How did you solve it? I am also facing the same issue while using getCalories(), it always return me an empty array.
