### ISSUE TITLE
getDistance not working

### ISSUE THREAD

**Issue by IronTony** [OvalMoney/react-native-fitness#71]
Hi all,

I was trying to using the permission and the method `getDistance` unfortunately the permission is not asked, just the permission for the steps, so neither the value is visible and usable

**Comment by geekmidas** [comment]
@IronTony Did you manage to get it working?

**Comment by IronTony** [comment]
@geekmidas nope, I used another package `rn-apple-healthkit` for iOS and `react-native-google-fit` for Android

**Comment by IronTony** [comment]
You can try `react-native-permissions` but I preferred to go the other way. Best of luck

**Comment by geekmidas** [comment]
@IronTony I tried using react-native-google-fit but it was the same issue on my side, it did not ask for permissions as well

**Comment by IronTony** [comment]
@geekmidas mmmm strange.
I did this:
```
onst googleFitFlow = useCallback(async () => {
    await GoogleFit.checkIsAuthorized().then(() => {
      GoogleFit.authorize(googleFitOptions)
        .then((authResult) => {
```
and it is working fine.

Just a quick hint, I think that this is not the right place to talk about another package 😉

**Comment by geekmidas** [comment]
@IronTony Thanks for the hint. Do you mind if I contact you privately on the email you have on GitHub?

**Comment by IronTony** [comment]
@geekmidas sure no problem

**Comment by geekmidas** [comment]
Thanks man @IronTony I sent you an email.
