### ISSUE TITLE
How To Logout

### ISSUE THREAD

**Issue by iyansr** [OvalMoney/react-native-fitness#75]
I was able to connect to Google Fitness, and Apple Healthkit,

Now how to disconnect or log out user from their account, in case they want to use different account, or they log out for my application

thanks

**Comment by Francesco-Voto** [comment]
Hi @iyansr,
with version 0.5.0 you are now able to logout or disconnect google fit

**Comment by iyansr** [comment]
thank @Francesco-Voto
