### ISSUE TITLE
RESULTS.UNAVAILABLE  on android 9 

### ISSUE THREAD

**Issue by cham1985** [OvalMoney/react-native-fitness#78]
Authorization is successful on Android 10, but on Android 9, the result returned by check(PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION) is RESULTS.UNAVAILABLE,

  <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION"/>

  <uses-permission android:name="android.gms.permission.ACTIVITY_RECOGNITION"/>

I have added these 2 permissions ,Does anyone know the reason  ?

**Comment by cham1985** [comment]
<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION"/>

  <uses-permission android:name="android.gms.permission.ACTIVITY_RECOGNITION"/>

**Comment by cham1985** [comment]
<img width="1173" alt="WechatIMG918" src="https://user-images.githubusercontent.com/7087874/99791820-2820ea80-2b61-11eb-86e4-3635f116e184.png">

**Comment by Francesco-Voto** [comment]
Hi @cham1985 . In android 9 you should ask runtime permissions. probably that is the reason. You have to add this check before. Anyway we are planning to insert this check on our side.
