### ISSUE TITLE
Bug: getDistance

### ISSUE THREAD

**Issue by m-ruhl** [OvalMoney/react-native-fitness#85]
Hello,

in the Readme and `index.d.ts` the method is defined as `getDistances()`
But the actual implementation is `getDistance()`

**Comment by Francesco-Voto** [comment]
Hello @m-ruhl ,

Thank you, It should be fixed with 0.5.1 now

**Comment by m-ruhl** [comment]
@Francesco-Voto thanks for the quick fix 👍
