### ISSUE TITLE
TypeError: _reactNativeFitness.default.requestPermissions is not a function.

### ISSUE THREAD

**Issue by praveen7557** [OvalMoney/react-native-fitness#9]
I tried to use this app in iOS like this

```
  componentDidMount() {
    Fitness.requestPermissions()
      .then((authorized) => {
        alert("authorized");
        //Do something
      })
      .catch((error) => {
        //Do something
      });
  }
```

But I'm getting this error.

TypeError: _reactNativeFitness.default.requestPermissions is not a function.

**Comment by scerelli** [comment]
@praveen7557 are you sure that you linked the package correctly? if you print `Fitness` what do you see?

**Comment by praveen7557** [comment]
I just did the linking automatically using `react-native link @ovalmoney/react-native-fitness`

This is what I'm getting when I print Fitness 

```
getDistance: ƒ getDistance(_ref2)
getSteps: ƒ getSteps(_ref)
__proto__: Object
```

**Comment by scerelli** [comment]
which version of RN are you using?

**Comment by praveen7557** [comment]
I am using RN 0.60

**Comment by scerelli** [comment]
Ok let me investigate this, i'll get back to you asap.

**Comment by scerelli** [comment]
@praveen7557 it works correctly to me, how are you importing the package?

**Comment by praveen7557** [comment]
This is my component 

```
import React, { Component } from 'react'
import { Text, View, DeviceEventEmitter } from 'react-native'
import Fitness from "@ovalmoney/react-native-fitness"



export default class Steps extends Component {

  componentDidMount() {

    console.log(Fitness);
    Fitness.requestPermissions()
      .then((authorized) => {
        alert("authorized");
        //Do something
      })
      .catch((error) => {
        //Do something
      });

  }

  render() {
    return (
      <View>
        <Text style={{ color: "black" }}> textInComponent </Text>
      </View>
    )
  }
}

```

**Comment by scerelli** [comment]
@praveen7557 please share also your `android/settings.gradle` the react-native fitness lines are enough

**Comment by praveen7557** [comment]
Actually, I am getting this error in iOS. It's working fine in Android.

**Comment by praveen7557** [comment]
@scerelli In Android, I'm trying to get steps, but when I do requestPermissions I'm getting false in the response. This is my code.

```
Fitness.requestPermissions()
      .then((authorized) => {
        debugger
        Fitness.getSteps({
          dates: { startDate: "08/12/2019", endDate: "08/13/2019" }
        }).then(res => {
          console.log(res);
          debugger
        }).catch(ex => {
          debugger
        })
      })
      .catch((error) => {
        //Do something
      });
```

Also, can you tell me how to form the request for the getSteps? Is it correct, what I did?

**Comment by scerelli** [comment]
@praveen7557  can you please try to do like this:

completely uninstall `@ovalmoney/react-native-fitness`

then do:
`yarn add @ovalmoney/react-native-fitness@github.com/OvalMoney/react-native-fitness`

tell me if it fix your problems both android and ios. You have to run pod install before building

**Comment by praveen7557** [comment]
@scerelli I am getting this error when I try to do `pod install` 

[!] No podspec found for `@ovalmoney` in `/Users/praveen/trippy/node_modules/@ovalmoney/react-native-fitness`.

Also can you give usage example for this as in 

```
Fitness.getSteps({
          dates: { startDate: "08/12/2019", endDate: "08/13/2019" }
        }).then(res => {
          console.log(res);
          debugger
        }).catch(ex => {
          debugger
        })
```
Is this the right way to do it?

**Comment by scerelli** [comment]
it's like this:

```
Fitness.getSteps({
    startDate,
    endDate,
  })
```

your podfile should be:
`pod 'react-native-fitness', :path => '../node_modules/@ovalmoney/react-native-fitness'`

**Comment by praveen7557** [comment]
@scerelli  I have the same in podfile
 ` pod 'react-native-fitness', :path => '../node_modules/@ovalmoney/react-native-fitness'`

**Comment by praveen7557** [comment]
@scerelli This is the sample repo. https://github.com/praveen7557/steps/tree/master/steps. 

In android also when I try to get steps, I am getting an error like `null reference`

**Comment by scerelli** [comment]
@praveen7557 I'm sorry, i just noticed we didn't mention that you need to create a google project on firebase to get this working.

We're updating the docs right now, in the meanwhile you can check here the fixes i made to your branch. IOs already working 

https://github.com/scerelli/steps/commit/77511f50d6d9f8434af0f0bf5e3a9a194ee4c584

**Comment by scerelli** [comment]
@praveen7557 check the new docs and the new release https://github.com/OvalMoney/react-native-fitness/releases/tag/v2.0.4

**Comment by praveen7557** [comment]
@scerelli Thanks. I will check and close the issue.

**Comment by praveen7557** [comment]
@scerelli For iOS, there is an error saying that `Health Kit not available`.

For Android, You said to generate a Client ID, but you didn't say where to put that ID, So I'm getting authorized as false.

**Comment by scerelli** [comment]
for iOS you have to enable health kit ofc, check here:
https://developer.apple.com/documentation/healthkit/setting_up_healthkit

for android, it's written in the guide we linked in the doc, the part that talks about debug keystore and release keystore.

https://developers.google.com/fit/android/get-api-key

**Comment by praveen7557** [comment]
@scerelli I generated the key using the documentation provided, but where should I use it?

**Comment by scerelli** [comment]
it's written here dude: https://developers.google.com/fit/android/get-api-key#find_your_apps_certificate_information

read it till the end pls

**Comment by praveen7557** [comment]
Sorry man, if I frustrated you. I generated the key using the documentation, but my question was, where should I use it? It doesn't say anything about where to put the Client ID.

bear with me, please.

**Comment by scerelli** [comment]
you don't have to put it anywhere just do this:

```
Go to the Google API Console.
Select a project, or create a new one. Use the same project for the Android and REST versions of your app.
Click Continue to enable the Fitness API.
Click Go to credentials.
Click New credentials, then select OAuth Client ID.
Under Application type select Android.
In the resulting dialog, enter your app's SHA-1 fingerprint and package name. For example:

BB:0D:AC:74:D3:21:E1:43:67:71:9B:62:91:AF:A1:66:6E:44:5D:75

com.example.android.fit-example

Click Create. Your new Android OAuth 2.0 Client ID and secret appear in the list of IDs for your project. An OAuth 2.0 Client ID is a string of characters, something like this:

780816631155-gbvyo1o7r2pn95qc4ei9d61io4uh48hl.apps.googleusercontent.com
```

**Comment by scerelli** [comment]
@praveen7557 did you manage to make it run?

**Comment by praveen7557** [comment]
@scerelli when I try to do this `const authorized = await Fitness.requestPermissions();` authorized is coming as false and getSteps is giving `null reference`

**Comment by scerelli** [comment]
I close this since we updated docs and you seems to have solved your issues, if you still have problem reopen it.

**Comment by emil-alexandrescu** [comment]
> @scerelli when I try to do this `const authorized = await Fitness.requestPermissions();` authorized is coming as false and getSteps is giving `null reference`. This is in android.

@praveen7557 Did you figure out this issue? I am getting exactly the same issue on Android.

**Comment by jakallergis** [comment]
I am too getting false from `Fitness.requestPermissions` even after I select a Google account in the prompt, and then I get a `null reference` error when I call `Fitness.getSteps` .
I have created the OAuth Client etc.

**Comment by Francesco-Voto** [comment]
Hi @jakallergis,

Can you select also what kind of permissions ( step, distance, etc) from the prompt?

**Comment by jakallergis** [comment]
Hi! I finally had the time to search more into it and solved it.

1) I didn't have these in:
```
implementation "com.google.android.gms:play-services-base:+"
implementation "com.google.android.gms:play-services-auth:+"
implementation "com.google.android.gms:play-services-fitness:+"
```

2. I also had the wrong package name. Because it said you'd find the package name from the manifest file but in there the `package` was different from the `applicationId` in my case. Turns out it needs the `applicationId`. Sorry for any confusion!
This one should be more clear tho.
‾\ _(ツ)_/‾

**Comment by tara-encora** [comment]
I am still facing the issue after following all the above solutions.
