### ISSUE TITLE
Fitness.requestPermissions(permissions) does not show permission allow modal

### ISSUE THREAD

**Issue by z3tsubouou** [OvalMoney/react-native-fitness#93]
`Fitness.requestPermissions(permissions)
.then((authorized) => {
console.log({authorized});
})
.catch((error) => {
console.log({error});
});`

> When i login into permission with my google account it keeps loading. I followed all steps and double checked all of them but does not stop loading keeps loading and does not ask me permission help :smiley:

**Comment by Princy-vaidya** [comment]
Same here, when I am login to google account it keeps loading. Please help ....

**Comment by Princy-vaidya** [comment]
Hey @z3tsubouou  have you got any solution for this?

**Comment by z3tsubouou** [comment]
> Hey @z3tsubouou  have you got any solution for this? 

Nope i still trying i think i need use client id somewhere but also i think it is not the issue. Maybe we need verify app. If you got any solution help me too. If i got solution i will help you.

**Comment by denkristoffer** [comment]
Assuming we're talking about iOS the permission request only works after you add Health to the app's capabilities in Xcode. Did you do that already?

**Comment by z3tsubouou** [comment]
> Assuming we're talking about iOS the permission request only works after you add Health to the app's capabilities in Xcode. Did you do that already?

Unfortunately i am talking about android version. After login with gmail never stop loading as you can see.
![Screenshot_20210117-093810.png](https://user-images.githubusercontent.com/25279427/104828773-cef6de00-58a7-11eb-996d-e13d575585ab.png)

**Comment by joaomdmoura** [comment]
Same issue here, after I select the account it shows up the loading modal and never finishes tagging along this one just in case

**Comment by XiNiHa** [comment]
Flutter equivalent https://github.com/krokyze/FitKit/issues/69 also having the same issue. I guess it's from the Google side. There is a workaround posted which is publishing the app on the API Console.

**Comment by joaomdmoura** [comment]
@z3tsubouou any updates there? publishing like to production? Because I'm using the internal testing through the play consle and it doesn't work still

**Comment by z3tsubouou** [comment]
> @z3tsubouou any updates there? publishing like to production? Because I'm using the internal testing through the play consle and it doesn't work still

nope i built my own native package 📦 (pedometer)

**Comment by anass05** [comment]
I had this error in debug mode on Android.
Adding the gmail account that's connected to google fit into google api console testers solved for me.

**Comment by juliomdsneto** [comment]
> I had this error in debug mode on Android.
> Adding the gmail account that's connected to google fit into google api console testers solved for me.

i'm having the same issue, but idk how to connect to google api console, can u tell me more?
